[package]
version = "0.0.0"
name = "frontend"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.28"

[dependencies]
seed = "0.8.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
