---
# This is a basic workflow to help you get started with Actions
name: pre-commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  # but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "main"
  pre-commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    # as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
      - id: pre-commit
        uses: blockchaintp/pre-commit-action@v1.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files}}
        env:
          SKIP: no-commit-to-branch
